### ISSUE TITLE
var vs let

### ISSUE THREAD

**Issue by avgx** [MusaShojen/UIKitLifeCycle#1]
https://github.com/MusaShojen/UIKitLifeCycle/blob/3b1056ff47d244f01d33687fd8ab373647c38a5d/LifeCycle/FoodView.swift#L14

заберись с `var` и `let`
чем отличаются.
когда и зачем использовать.

**Comment by MusaShojen** [comment]
Действительно стоило сделать переменные let. 

Var нужен для случаев, когда значения переменных будут меняться, а let , когда мы точно знаем, что они не изменятся. Плюс когда делаем let, компилятор может оптимизировать код на основе того, что он знает заранее значения переменных let.
