### ISSUE TITLE
провести рефакторинг.

### ISSUE THREAD

**Issue by avgx** [MusaShojen/UIKitLifeCycle#2]
https://github.com/MusaShojen/UIKitLifeCycle/blob/3b1056ff47d244f01d33687fd8ab373647c38a5d/LifeCycle/NetWorking.swift#L13

а что если тут несколько методов?
что такое `private`?

**Comment by MusaShojen** [comment]
Добавил private к функции которая делает ссылку. Private нужен, чтобы ограничить использование какой-либо функции рамками класса в котором она описана. То есть если говорить про данный класс - функцию которая создает URL может использовать только другой метод из класса NetWorking
